apply plugin: 'com.android.application'

android {
    namespace 'com.mrpoid.mrpliset' // <--- WAJIB DITAMBAHKAN UNTUK AGP 8+
    compileSdkVersion 34 // <--- DIUBAH DARI 27
    // buildToolsVersion dihapus saja, otomatis mengikuti compileSdk

    defaultConfig {
        applicationId "com.mrpoid.mrpliset"
        minSdkVersion 17
        targetSdkVersion 34 // <--- DIUBAH DARI 26
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    
    // Tambahan untuk kompatibilitas Java 17
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':lib')
    // DIUBAH DARI com.android.support MENJADI ANDROIDX
    implementation 'androidx.appcompat:appcompat:1.6.1' 
}
